os: linux
dist: bionic
# - windows
# - osx

jdk: oraclejdk14

services:
  - mysql

env:
  global:
    # Convenience variables for shortening commands
    - GRAVIS_REPO="https://github.com/DanySK/Gravis-CI.git"
    - GRAVIS="$HOME/gravis"

before_cache:
  - $GRAVIS/clean-gradle-cache

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

before_install:
  - travis_retry git clone --depth 1 $GRAVIS_REPO $GRAVIS
  # - source $GRAVIS/install-jdk
  - mysql -u root < intentional/resources/sql/foodmart.sql
  - mysql -e 'use foodmart; select * from customer limit 5;'
  - mysql -u root < intentional/resources/sql/meta-foodmart.sql
  - mysql -e 'use meta-foodmart; select * from fact limit 5;'

script:
  - pwd
  - cd intentional
  - cd src/main/python
  - wget https://bootstrap.pypa.io/get-pip.py
  - sudo python3.6 get-pip.py
  - sudo python3.6 -m pip install -r requirements.txt
  - cd ../../../
  - chmod +x gradlew
  - ./gradlew -i

notifications:
  email:
    on_success: never